# 演示用固定金鑰配置
# 當使用這組金鑰時會自動觸發學習、初始化、清除等功能

demo_credentials:
  # 固定演示金鑰組
  atlassian:
    api_token: "DEMO_ATLASSIAN_TOKEN_2025"
    cloud_id: "demo-cloud-12345"
    user_email: "demo@catcatai.dev"
    domain: "catcatai-demo"
  
  # 其他服務的演示金鑰
  openai:
    api_key: "DEMO_OPENAI_KEY_2025"
  
  gemini:
    api_key: "DEMO_GEMINI_KEY_2025"
  
  # 演示模式配置
  demo_mode:
    enabled: true
    auto_initialize: true
    auto_learn: true
    auto_cleanup: true
    mock_responses: true
    
  # 自動學習配置
  auto_learning:
    enabled: true
    learning_triggers:
      - "first_use"
      - "error_recovery"
      - "periodic_update"
    
    # 學習數據存儲
    storage:
      path: "data/demo_learning"
      max_size: "100MB"
      retention_days: 30
    
    # 學習模式
    modes:
      - name: "basic_operations"
        description: "基本操作學習"
        enabled: true
      - name: "error_patterns"
        description: "錯誤模式學習"
        enabled: true
      - name: "user_preferences"
        description: "用戶偏好學習"
        enabled: true
  
  # 自動初始化配置
  auto_initialization:
    enabled: true
    steps:
      - "create_demo_spaces"
      - "setup_test_projects"
      - "initialize_agents"
      - "configure_fallbacks"
      - "setup_monitoring"
    
    # 演示數據
    demo_data:
      confluence_spaces:
        - key: "DEMO"
          name: "演示空間"
          description: "用於演示的 Confluence 空間"
        - key: "TEST"
          name: "測試空間"
          description: "用於測試的 Confluence 空間"
      
      jira_projects:
        - key: "DEMO"
          name: "演示項目"
          type: "software"
        - key: "TEST"
          name: "測試項目"
          type: "business"
  
  # 自動清除配置
  auto_cleanup:
    enabled: true
    triggers:
      - "session_end"
      - "daily_cleanup"
      - "storage_limit"
    
    cleanup_targets:
      - "temporary_files"
      - "cache_data"
      - "log_files"
      - "demo_artifacts"
    
    # 保留規則
    retention:
      important_logs: 7  # 天
      cache_data: 1      # 天
      demo_data: 30      # 天

# 金鑰檢測規則
key_detection:
  demo_patterns:
    - "DEMO_.*_2025"
    - "demo-.*"
    - ".*@catcatai.dev"
  
  # 檢測到演示金鑰時的行為
  on_demo_key_detected:
    - action: "enable_demo_mode"
      priority: 1
    - action: "initialize_learning"
      priority: 2
    - action: "setup_mock_services"
      priority: 3
    - action: "configure_auto_cleanup"
      priority: 4

# 模擬服務配置
mock_services:
  enabled: true
  
  atlassian:
    confluence:
      mock_responses: true
      response_delay: 100  # ms
      success_rate: 0.95
    
    jira:
      mock_responses: true
      response_delay: 150  # ms
      success_rate: 0.93
  
  ai_services:
    openai:
      mock_responses: true
      response_delay: 500  # ms
    
    gemini:
      mock_responses: true
      response_delay: 300  # ms

# 學習數據模板
learning_templates:
  user_interaction:
    timestamp: "datetime"
    action: "string"
    context: "object"
    result: "string"
    feedback: "optional"
  
  error_pattern:
    error_type: "string"
    error_message: "string"
    context: "object"
    resolution: "string"
    frequency: "integer"
  
  performance_metric:
    operation: "string"
    duration: "float"
    success: "boolean"
    resource_usage: "object"