packages:
  - 'packages/*'
  - 'apps/*'
  - 'apps/desktop-app/electron_app'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - electron
  - es5-ext
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
