packages:
  - 'packages/*'
  - 'apps/*'
  - 'apps/*/electron_app'

overrides:
  "@eslint/eslintrc>minimatch": "3.1.4"
  "@humanwhocodes/config-array>minimatch": "3.1.4"
  "flat-cache>flatted": "3.4.2"
  "axios>form-data": "4.0.6"

allowBuilds:
  electron: true
  electron-winstaller: true
  sharp: true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - electron
  - es5-ext
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
