packages:
  - 'packages/*'
  - 'apps/*'
  - 'apps/*/electron_app'

allowBuilds:
  electron: true
  electron-winstaller: true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - electron
  - es5-ext
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
