// By embedding the audio as base64 data URIs, we eliminate network requests,
// making playback instant and immune to network errors.

// --- Background Music ---
// Note: These are simple, programmatically generated loops to provide distinct moods.
export const calmMusic = 'data:audio/wav;base64,UklGRpAAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhZgAAAFRcV11gY2NlZmZpaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2A==';
export const actionMusic = 'data:audio/wav;base64,UklGRkIAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhQAAAABgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGA==';
export const suspenseMusic = 'data:audio/wav;base64,UklGRqAAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAAABkYXRhpoAAAAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v8PHy8/T19vf4+fr7/P3+/wACAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v8PHy8/T19vf4+fr7/P3+/w==';
export const mysteriousMusic = 'data:audio/wav;base64,UklGRqoAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAAABkYXRhqAAAAH9/f35+fn19fXx8fHt7e3p6eno6Ojk5OTg4ODc3NzY2NjU1NTQ0NDMzMy8vLywsLCsrKygoKCcnJyYmJiUlJSQkJCMjIyIiIiEhISAgIB8fHx4eHh0dHRwcHBoaGhkZGRgYGBcXFxYWFhUVFRQUFBMTExISEhERERAPDw4ODg0NDQwMDAwLCwoKCgkJCAgHBwYGBQUFBAMDAgICAgEBAQAAAAAsLCwoKCgnJycmJiYlJSQkJCMjIyIiIiEhISAgIB8fHx4eHh0dHRwcHBoaGhkZGRgYGBcXFxYWFhUVFRQUFBMTExISEhERERAPDw4ODg0NDQwMDAwLCwoKCgkJCAgHBwYGBQUFBAMDAgICAgEBAQAA';
export const epicMusic = 'data:audio/wav;base64,UklGRkYAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhQgAAAPz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pw==';
export const sadMusic = 'data:audio/wav;base64,UklGRkIAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhQAAAAAwMGBgWFBQODgwMCgoICAgGBgQEBAICAgAAAAAAAQEBAQEBAQEBAQEBAQECAgIDAwQEBAUFBQYGBgcHBwgICAkJCQoKCgsLDAwMDQ0ODg4PDw8QEBA=';
export const horrorMusic = 'data:audio/wav;base64,UklGRpAAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhZgAAAGD/uv+k/9v/mP+P/8f/wf+a/7r/2v/k/9//s/+v/5L/lv+5/8n/4v/v//L/7b/mP+T/5L/ov/D/9v/5//f/8P/q/+P/4f/S/7T/ov+T/4//j/+Q/5v/sf/J/9L/5//x//L/7P/m/+H/3f/S/7z/rP+j/5f/kv+P/4v/i/+N/5P/nP+x/7//y//a/+X/8v/v/+v/5//e/9b/yP+6/6v/pP+c/5j/lP+T/5D/jf+K/4n/j/+S/5f/oP+u/7r/yP/X/+D/6v/z/wD/AP/x/+r/4v/Y/8b/tv+p/6D/mv+W/5H/jP+J/4b/hf+J/47/kv+Y/5z/qf+1/8L/1v/d/+j/8f/5//z/9//s/+T/3P/S/8H/tf+o/6D/mf+V/5H/jP+H/4T/gv+E/4j/jv+T/5f/nP+j/6v/uv/G/9b/3f/o//H/+v/8//r/7P/l/9z/0v/B/7X/qP+h/5r/lf+R/4z/h/+B/4D/gP+D/4f/i/+N/5D/lP+Y/53/o/+q/7n/xv/V/97/6f/y//v//f/y/+n/3v/V/8b/uf+q/6P/nf+Y/5T/kP+M/4b/f/99/33/gP+G/4n/jf+Q/5T/mP+d/6P/q/+5/8b/1f/e/+r/8v/7/wA=';