# HSP Fallback協議配置
hsp_fallback:
  # 是否啟用fallback協議
  enabled: true
  
  # Fallback協議優先級配置
  protocols:
    # HTTP協議 - 最高優先級
    http:
      priority: 3
      enabled: true
      host: "127.0.0.1"
      port: 8765
      timeout: 30
      
    # 文件協議 - 中等優先級  
    file:
      priority: 2
      enabled: true
      base_path: "data/fallback_comm"
      poll_interval: 0.5
      max_file_size: 10485760  # 10MB
      
    # 內存協議 - 最低優先級（本地通訊）
    memory:
      priority: 1
      enabled: true
      queue_size: 1000
      
  # 消息配置
  message:
    # 默認重試次數
    default_max_retries: 3
    # 默認TTL（秒）
    default_ttl: 300
    # 健康檢查間隔（秒）
    health_check_interval: 30
    
  # 日誌配置
  logging:
    level: "INFO"
    log_fallback_usage: true
    log_protocol_switches: true
    
# HSP主協議配置
hsp_primary:
  # MQTT配置
  mqtt:
    broker_address: "127.0.0.1"
    broker_port: 1883
    keepalive: 60
    qos_default: 1
    
  # 連接配置
  connection:
    # 連接超時（秒）
    timeout: 10
    # 重連間隔（秒）
    reconnect_interval: 5
    # 最大重連次數
    max_reconnect_attempts: 3
    
  # 健康檢查
  health_check:
    # 檢查間隔（秒）
    interval: 60
    # 超時時間（秒）
    timeout: 5