@echo off
echo Moving scattered test files to backup directory...

move /y "D:\Projects\Unified-AI-Project\check_test_collection.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\debug_test_collection.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\enable_commented_tests.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\find_skipped_tests.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\intelligent_test_generator.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\maintain_test_suite.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\optimize_test_suite.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\project_function_test_mapping.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\quick_test_concept_models.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\run_hsp_tests.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\run_simple_hsp_test.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\run_tests_with_compat.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\run_verification_test.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\simple_test_optimizer.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_alpha_upgrade.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_api.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_api_with_delay.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_audio_service_direct.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_automated_defect_detector.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_code_model_upgrade.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_compat_fix.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_concept_models_training.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_coverage_analyzer.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_dependency_manager.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_fixed_modules_final.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_gmqtt_import.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_intelligent_test_generator.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_logic_parser.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_logic_tool.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_math_model.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_math_tool.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_model_integration.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_modules.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_modules_with_output.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_multi_llm_import.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_path.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_performance_benchmark.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_security_improvements.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_server.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_tool_call_chain.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_tool_context_manager.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_trained_models.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_type_fixes.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\test_unused_call_result.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"

echo Moving backend test files...
move /y "D:\Projects\Unified-AI-Project\apps\backend\check_test_results.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\debug_patch_test.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\debug_test.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\extract_latest_failures.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\final_test.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\run_fixed_tests.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\run_hsp_simple_test.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\run_hsp_test.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\run_test.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\run_test_direct.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\run_test_fix.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\run_test_subprocess.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\simple_hsp_test.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\simple_test.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\temp_test_debug.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\test_agi_integration.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\test_apple_inc.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\test_capital_of.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\test_capital_of_debug.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\test_chromadb_fix.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\test_content_analyzer.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\test_content_analyzer_fix.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\test_data_analysis_debug.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\test_debug.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\test_env.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\test_fix.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\test_fixes.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\test_fix_debug.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\test_hsp_fixture.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\test_import.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\test_json_fix.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\test_modules.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"

echo Moving backend scripts test files...
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\automated_integration_test_pipeline.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\continuous_test_improvement.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\demo_test_result_processing.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\generate_test_report.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\integration_test.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\process_test_results.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\run_integration_tests.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\smart_test_runner.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\test_chromadb_fix.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\test_data_manager.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\test_environment_manager.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\test_fixes.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\test_fix_demo.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\test_quality_assessor.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\test_result_analyzer.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\test_result_feedback.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\test_result_visualizer.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\test_runner.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\tools\tools\scripts\test_smart_executor.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"

echo Moving backend src test files...
move /y "D:\Projects\Unified-AI-Project\apps\backend\src\ai\concept_models\integration_test.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\src\ai\test_utils\deadlock_detector.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"
move /y "D:\Projects\Unified-AI-Project\apps\backend\src\hsp\bridge\test_message_bridge.py" "D:\Projects\Unified-AI-Project\all_test_backups\scattered_tests\"

echo All scattered test files have been moved to backup directory.
pause