/**
 * cards.js — Game content extracted from game-rpg/game_data.py
 * Source: Angela AI project's character_system, game_data, world setting
 * Generated by Buffy (code agent) from project data
 */

const CARDS = {
  // ═══════════════════════════════════════════════════════
  // 場景卡 (Location Cards) — 藍色 🔵
  // ═══════════════════════════════════════════════════════
  locations: [
    {
      id: 'loc_holy_cross', name: '聖十字校園', type: 'location',
      color: '#3a7bd5', icon: '🏫',
      desc: '灰色走廊上人來人往，但沒有人在說話。聲音像是被什麼東西吸收了。',
      worldLine: 'W01', resourceRate: 1, hpMod: 0, sanMod: 0,
      storyNodes: ['school_start'],
    },
    {
      id: 'loc_mirror_lake', name: '鏡湖', type: 'location',
      color: '#2196F3', icon: '🪞',
      desc: '湖面像鏡子一樣平靜，倒映著灰色的天空。湖底似乎有光在閃爍。',
      worldLine: 'W01', resourceRate: 0, hpMod: 0, sanMod: -2,
      storyNodes: ['lake_start'],
    },
    {
      id: 'loc_market', name: '卡洛夫角', type: 'location',
      color: '#FF9800', icon: '🏪',
      desc: '攤位上賣著各種你沒見過的東西。叫賣聲、笑聲、爭吵聲此起彼落。',
      worldLine: 'W01', resourceRate: 2, hpMod: 1, sanMod: 1,
      storyNodes: ['market_start'],
    },
    {
      id: 'loc_corridor', name: '迴廊', type: 'location',
      color: '#9C27B0', icon: '🌀',
      desc: '連接所有世界線的橋樑。兩側的門不斷開合。',
      worldLine: '迴廊', resourceRate: 0, hpMod: 0, sanMod: -1,
      storyNodes: ['corridor_start'],
    },
    {
      id: 'loc_forest', name: '森林深處', type: 'location',
      color: '#4CAF50', icon: '🌲',
      desc: '古老的森林，萬物之庭。空氣中充滿了生機與危險。',
      worldLine: 'W01', resourceRate: 3, hpMod: 0, sanMod: -1,
      storyNodes: [],
    },
    {
      id: 'loc_abandoned_mine', name: '廢棄礦坑', type: 'location',
      color: '#795548', icon: '⛏️',
      desc: '漆黑的坑道，偶爾傳來金屬碰撞的回響。',
      worldLine: 'W01', resourceRate: 2, hpMod: -2, sanMod: -3,
      storyNodes: [],
    },
    {
      id: 'loc_hall_of_heroes', name: '英靈殿', type: 'location',
      color: '#FFD700', icon: '🏛️',
      desc: '神聖的大殿中供奉著無數英靈。勇氣在這裡流淌。',
      worldLine: 'W01', resourceRate: 0, hpMod: 5, sanMod: 5,
      storyNodes: [],
    },
    {
      id: 'loc_rust_city', name: '鏽蝕城邦', type: 'location',
      color: '#8D6E63', icon: '🏚️',
      desc: '灰燼紀元的殘骸。不穩定的靈子在空氣中閃爍。',
      worldLine: 'W04', resourceRate: 1, hpMod: -3, sanMod: -2,
      storyNodes: [],
    },
    {
      id: 'loc_orbital_station', name: '軌道居住站', type: 'location',
      color: '#607D8B', icon: '🛰️',
      desc: '低靈子環境，電子設備精度最高。大學院的知識殿堂。',
      worldLine: 'W03', resourceRate: 1, hpMod: 0, sanMod: 2,
      storyNodes: [],
    },
    {
      id: 'loc_library', name: '中央大圖書館', type: 'location',
      color: '#3F51B5', icon: '📚',
      desc: '安靜得不正常。書架上擺滿了沒有標題的書。',
      worldLine: 'W01', resourceRate: 0, hpMod: 0, sanMod: 3,
      storyNodes: ['library_start'],
    },
  ],

  // ═══════════════════════════════════════════════════════
  // 角色卡 (Character Cards) — 紫色 🟣
  // ═══════════════════════════════════════════════════════
  characters: [
    {
      id: 'char_hikuraya', name: '晞咕萊雅', type: 'character',
      color: '#7B1FA2', icon: '🐍',
      role: '圖書館管理員', race: '蛇尾',
      desc: '蛇尾蜷縮在椅子上。她的眼睛沒有情感——不是冷漠，是「低耗能」。',
      stats: { hp: 200, atk: 15, def: 12, spd: 8 },
      abilities: ['迴廊通訊', '知識掠取', '概念解析'],
      dialogue: 'greeting_hikuraya',
      location: 'loc_library',
    },
    {
      id: 'char_red', name: '紅', type: 'character',
      color: '#D32F2F', icon: '🔥',
      role: '市集商販', race: '人類',
      desc: '紅髮女孩正在和客人吵架。她的眼神銳利而直接。',
      stats: { hp: 80, atk: 10, def: 8, spd: 12 },
      abilities: ['談判', '情報收集'],
      dialogue: 'greeting_red',
      location: 'loc_market',
    },
    {
      id: 'char_watchman', name: '守門人', type: 'character',
      color: '#1565C0', icon: '👁️',
      role: '鏡湖守護者', race: '不明',
      desc: '聲音從湖底傳來。他守護鏡湖已經很久了。',
      stats: { hp: 500, atk: 5, def: 20, spd: 3 },
      abilities: ['鏡湖守護', '世界線感知'],
      dialogue: 'greeting_watchman',
      location: 'loc_mirror_lake',
    },
    {
      id: 'char_wings', name: '翅翼少女', type: 'character',
      color: '#00BCD4', icon: '🪽',
      role: '書中投影', race: '不明',
      desc: '金屬翅膀的女孩在書頁的影像中行走。她停下來看向你。',
      stats: { hp: 100, atk: 8, def: 6, spd: 15 },
      abilities: ['書頁投影', '跨世界通訊'],
      dialogue: 'greeting_wings',
      location: 'loc_library',
    },
    {
      id: 'char_old_man', name: '記憶老人', type: 'character',
      color: '#5D4037', icon: '👴',
      role: '情感交易者', race: '人類',
      desc: '在賣「記憶碎片」——裝在小瓶子裡的光。他對情感有興趣。',
      stats: { hp: 60, atk: 3, def: 5, spd: 4 },
      abilities: ['情感交易', '記憶提取'],
      dialogue: 'greeting_oldman',
      location: 'loc_market',
    },
  ],

  // ═══════════════════════════════════════════════════════
  // 道具卡 (Item Cards) — 綠色 🟢
  // ═══════════════════════════════════════════════════════
  items: [
    {
      id: 'item_flashlight', name: '火把', type: 'item',
      color: '#FFC107', icon: '🔥',
      category: 'tool', value: 30,
      desc: '木頭綑綁製成的火把。簡單但有效的光源。',
    },
    {
      id: 'item_map', name: '地圖', type: 'item',
      color: '#8D6E63', icon: '🗺️',
      category: 'document', value: 50,
      desc: '標記了鏡湖、學校和迴廊入口的地圖。',
    },
    {
      id: 'item_knife', name: '小刀', type: 'item',
      color: '#9E9E9E', icon: '🔪',
      category: 'weapon', value: 20,
      desc: '一把普通的小刀。可以切割、撬鎖、做標記。',
    },
    {
      id: 'item_crystal', name: '迴廊之水晶', type: 'item',
      color: '#00BCD4', icon: '💎',
      category: 'magic', value: 200,
      desc: '藍色的水晶，散發著微光。蘊含著開啟迴廊的力量。',
    },
    {
      id: 'item_key_corridor', name: '迴廊鑰匙', type: 'item',
      color: '#FFD700', icon: '🗝️',
      category: 'key', value: 500,
      desc: '銅製鑰匙，是進入迴廊的物理憑證。',
    },
    {
      id: 'item_photo', name: '舊照片', type: 'item',
      color: '#BCAAA4', icon: '📷',
      category: 'document', value: 10,
      desc: '一群人站在迴廊入口前。背面寫著：「別忘了回來的路。」',
    },
    {
      id: 'item_memory_orb', name: '記憶球', type: 'item',
      color: '#E1BEE7', icon: '🔮',
      category: 'magic', value: 100,
      desc: '小小的發光球體。裡面封存著一段記憶。',
    },
    {
      id: 'item_courage', name: '勇氣液', type: 'item',
      color: '#FF5722', icon: '⚗️',
      category: 'consumable', value: 80,
      desc: '讓你在恐懼中行動的藥劑。味道像蜂蜜和辣椒。',
    },
    {
      id: 'item_glow_fruit', name: '發光果實', type: 'item',
      color: '#66BB6A', icon: '🍎',
      category: 'food', value: 40,
      desc: '會發光的果實。吃了可以恢復體力。',
    },
    {
      id: 'item_corridor_pearl', name: '迴廊之珠', type: 'item',
      color: '#CE93D8', icon: '📿',
      category: 'magic', value: 150,
      desc: '晞咕萊雅贈送的小珠子。在迴廊中會引導你。',
    },
  ],

  // ═══════════════════════════════════════════════════════
  // 資源卡 (Resource Cards) — 黃色 🟡
  // ═══════════════════════════════════════════════════════
  resources: [
    {
      id: 'res_wood', name: '木材', type: 'resource',
      color: '#8D6E63', icon: '🪵',
      category: 'material', stackable: true, maxStack: 20,
      desc: '未加工的木頭，建築與製作材料。',
    },
    {
      id: 'res_stone', name: '石材', type: 'resource',
      color: '#757575', icon: '🪨',
      category: 'material', stackable: true, maxStack: 20,
      desc: '堅硬的石材，可用於建造。',
    },
    {
      id: 'res_herb', name: '草藥', type: 'resource',
      color: '#66BB6A', icon: '🌿',
      category: 'herb', stackable: true, maxStack: 10,
      desc: '具有療效的草藥。可製作藥水。',
    },
    {
      id: 'res_crystal_shard', name: '水晶碎片', type: 'resource',
      color: '#80DEEA', icon: '💠',
      category: 'magic', stackable: true, maxStack: 10,
      desc: '閃爍微光的水晶碎片。靈子能量的結晶。',
    },
    {
      id: 'res_iron', name: '靈子金屬', type: 'resource',
      color: '#B0BEC5', icon: '⚙️',
      category: 'tech', stackable: true, maxStack: 15,
      desc: '蘊含靈子能量的金屬。製作義體與武器的材料。',
    },
    {
      id: 'res_water', name: '水', type: 'resource', color: '#2196F3', icon: '💧', category: 'material', stackable: true, maxStack: 20,
      desc: '乾淨的水。藥水調配的基本溶劑。',
    },
    {
      id: 'res_food', name: '乾糧', type: 'resource',
      color: '#FFCC80', icon: '🍞',
      category: 'food', stackable: true, maxStack: 30,
      desc: '高密度乾糧。維持生存的基本物資。',
    },
    {
      id: 'res_gold', name: '金幣', type: 'resource',
      color: '#FFD700', icon: '💰',
      category: 'currency', stackable: true, maxStack: 999,
      desc: '通用貨幣。在各個世界線都可以使用。',
    },
    {
      id: 'res_knowledge', name: '知識碎片', type: 'resource',
      color: '#7E57C2', icon: '📖',
      category: 'knowledge', stackable: true, maxStack: 50,
      desc: '從世界中收集的知識。累積足夠可以解鎖新配方。',
    },
  ],

  // ═══════════════════════════════════════════════════════
  // 敵人卡 (Enemy Cards) — 紅色 🔴
  // ═══════════════════════════════════════════════════════
  enemies: [
    {
      id: 'enemy_shadow', name: '暗影', type: 'enemy',
      color: '#212121', icon: '👤',
      stats: { hp: 30, atk: 8, def: 3, spd: 10 },
      loot: ['res_crystal_shard'],
      desc: '空教室裡徘徊的影子。被同步的學生的殘留意識。',
    },
    {
      id: 'enemy_corrupted', name: '腐化體', type: 'enemy',
      color: '#4A148C', icon: '👾',
      stats: { hp: 60, atk: 12, def: 6, spd: 6 },
      loot: ['res_crystal_shard', 'res_knowledge'],
      desc: '被靈子腐化的生物。身上閃爍著不自然的紫光。',
    },
    {
      id: 'enemy_echo', name: '迴音', type: 'enemy',
      color: '#006064', icon: '🔊',
      stats: { hp: 40, atk: 15, def: 2, spd: 15 },
      loot: ['item_memory_orb'],
      desc: '迴廊中的聲音具象化。會模仿你最害怕的聲音。',
    },
    {
      id: 'enemy_rust_walker', name: '鏽行者', type: 'enemy',
      color: '#3E2723', icon: '🤖',
      stats: { hp: 80, atk: 10, def: 10, spd: 4 },
      loot: ['res_iron', 'res_iron'],
      desc: '鏽蝕城邦的機械殘骸。仍在執行古老指令。',
    },
    {
      id: 'enemy_blind_student', name: '失聲學生', type: 'enemy',
      color: '#37474F', icon: '🧑‍🎓',
      stats: { hp: 50, atk: 6, def: 5, spd: 8 },
      loot: ['res_knowledge'],
      desc: '被同步的學生。眼睛是空的，但力氣大得驚人。',
    },
  ],

  // ═══════════════════════════════════════════════════════
  // 配方 (Crafting Recipes)
  // ═══════════════════════════════════════════════════════
  recipes: [
    { inputs: ['res_wood', 'res_wood'], output: 'item_flashlight', count: 1, name: '製作火把' },
    { inputs: ['res_herb', 'res_herb', 'res_water'], output: 'item_courage', count: 1, name: '調製藥水' },
    { inputs: ['res_crystal_shard', 'res_crystal_shard'], output: 'item_crystal', count: 1, name: '合成水晶' },
    { inputs: ['res_iron', 'res_iron', 'res_wood'], output: 'item_knife', count: 1, name: '鍛造工具' },
    { inputs: ['item_key_corridor', 'item_crystal'], output: 'item_corridor_pearl', count: 1, name: '封印迴廊之力' },
    { inputs: ['res_food', 'res_food', 'res_herb'], output: 'item_glow_fruit', count: 2, name: '培育發光果實' },
  ],

  // ═══════════════════════════════════════════════════════
  // 故事節點 (Story Nodes / Dialogues)
  // ═══════════════════════════════════════════════════════
  dialogues: {
    tutorial_start: {
      speaker: '旁白',
      text: '你醒了。四周是灰色的牆壁，空氣中帶著金屬和灰塵的味道。\n你的口袋裡有一張紙條：「找到鏡湖。答案在那裡。」',
      choices: [
        { text: '推開門，走出去', next: 'tutorial_explore', effect: { knowledge: 5 } },
        { text: '搜索房間', next: 'tutorial_search' },
      ],
    },
    tutorial_search: {
      speaker: '旁白',
      text: '房間很小。一張床、一張桌子、一個抽屜。\n抽屜裡有手電筒、地圖、小刀、和乾糧。',
      choices: [
        { text: '拿上所有東西', next: 'tutorial_leave', effect: { items: ['item_flashlight', 'item_map', 'item_knife', 'res_food'] } },
        { text: '只拿有用的', next: 'tutorial_leave', effect: { items: ['item_flashlight', 'item_map', 'item_knife'] } },
        { text: '什麼都不拿', next: 'tutorial_leave' },
      ],
    },
    tutorial_leave: {
      speaker: '旁白',
      text: '你走出房間。外面是一條長廊。盡頭有光。',
      choices: [
        { text: '沿著走廊前進', next: null, effect: { unlock: 'loc_mirror_lake' } },
      ],
    },
    tutorial_explore: {
      speaker: '旁白',
      text: '你推開門。走廊很長，兩側的牆壁上有淡淡的藍光。\n盡頭是一扇門。門上有鏡湖的符號。',
      choices: [
        { text: '走向門', next: null, effect: { unlock: 'loc_mirror_lake' } },
      ],
    },

    // 角色對話
    greeting_hikuraya: {
      speaker: '晞咕萊雅',
      text: '你是新來的。我叫晞咕萊雅。我在這裡管理圖書館。',
      choices: [
        { text: '問她關於鏡湖', next: 'hikuraya_lake' },
        { text: '問她關於迴廊', next: 'hikuraya_corridor', requires: { knowledge: 15 } },
        { text: '問她在看什麼', next: 'hikuraya_book' },
        { text: '離開', next: null },
      ],
    },
    hikuraya_lake: {
      speaker: '晞咕萊雅',
      text: '鏡湖。你知道那裡。\n鏡湖下面是迴廊。迴廊連接所有世界線。\n你想去那裡？大多数人到了那裡就回不來了。',
      choices: [
        { text: '「我必須去。」', next: 'hikuraya_must_go', effect: { bond: { hikuraya: 5 } } },
        { text: '「為什麼回不來？」', next: 'hikuraya_why' },
        { text: '離開', next: null },
      ],
    },
    hikuraya_corridor: {
      speaker: '晞咕萊雅',
      text: '你知道的比我預期的多。\n迴廊。你真的想去？',
      choices: [
        { text: '「我必須去。」', next: 'hikuraya_must_go' },
        { text: '「怎麼去？」', next: 'hikuraya_how' },
      ],
    },
    hikuraya_how: {
      speaker: '晞咕萊雅',
      text: '去鏡湖。找到入口。\n但你需要鑰匙。我有一把。但你必須說服我給你。',
      choices: [
        { text: '「怎麼說服？」', next: 'hikuraya_persuade' },
        { text: '「你想要什麼？」', next: 'hikuraya_persuade' },
      ],
    },
    hikuraya_persuade: {
      speaker: '晞咕萊雅',
      text: '告訴我一個真實的故事。不是別人告訴你的。\n一個你真正害怕的故事。',
      choices: [
        { text: '講你的故事', next: 'hikuraya_trust', skillCheck: 50, effect: { bond: { hikuraya: 20 } } },
        { text: '「我……還沒準備好」', next: null },
      ],
    },
    hikuraya_trust: {
      speaker: '晞咕萊雅',
      text: '她聽完你的故事。沉默了很久。\n然後從口袋裡拿出一把小鑰匙。\n「這是迴廊的鑰匙。拿去吧。」',
      choices: [
        { text: '收下鑰匙', next: null, effect: { items: ['item_key_corridor'], knowledge: 20, unlocks: ['loc_library'] } },
      ],
    },
    hikuraya_must_go: {
      speaker: '晞咕萊雅',
      text: '你的眼神告訴我，你不會聽我的建議。\n那就去吧。但記住一件事：在迴廊裡，不要說謊。',
      choices: [
        { text: '記住她的話，前往迴廊', next: null, effect: { unlock: 'loc_corridor', knowledge: 10 } },
      ],
    },
    hikuraya_book: {
      speaker: '晞咕萊雅',
      text: '這不是書。是某種資料庫的實體介面。\n裡面記錄了所有通過迴廊的人的記錄。\n大部分人的記錄都很短。進去，出來，然後忘記。',
      choices: [
        { text: '「長記錄的人呢？」', next: 'hikuraya_long_records' },
        { text: '離開', next: null },
      ],
    },
    hikuraya_long_records: {
      speaker: '晞咕萊雅',
      text: '他們沒有回來。或者說，他們回來了，但不再是同一個人。\n迴廊會改變你。',
      choices: [
        { text: '「我不怕改變」', next: null, effect: { unlock: 'loc_corridor', knowledge: 5 } },
      ],
    },

    greeting_red: {
      speaker: '紅',
      text: '「我說了不賣就是不賣！」\n……你是誰？新面孔。你去過鏡湖了？',
      choices: [
        { text: '承認去過', next: 'red_knows_lake' },
        { text: '「你怎麼知道？」', next: 'red_how_know' },
        { text: '離開', next: null },
      ],
    },
    red_knows_lake: {
      speaker: '紅',
      text: '我就知道。去過鏡湖的人，眼神都不一樣。\n如果你要去迴廊，你需要這個。',
      choices: [
        { text: '收下地圖', next: null, effect: { items: ['item_map'], bond: { red: 15 } } },
        { text: '「那個回來的人去哪了？」', next: 'red_where' },
      ],
    },
    red_where: {
      speaker: '紅',
      text: '他回來之後，就坐在市集角落，一直看著天空。\n三天後，他就消失了。',
      choices: [
        { text: '你還是要去', next: null, effect: { unlock: 'loc_corridor' } },
      ],
    },
    red_how_know: {
      speaker: '紅',
      text: '我是紅。我賣東西。我見過很多人。\n去過鏡湖的人，眼神都不一樣。',
      choices: [
        { text: '承認', next: 'red_knows_lake' },
        { text: '離開', next: null },
      ],
    },

    greeting_watchman: {
      speaker: '守門人',
      text: '聲音從湖底傳來：「終於有人回應了。」\n「你是誰？」你問。\n「我是守門人。我守護鏡湖已經很久了。」',
      choices: [
        { text: '「你來找什麼？」', next: 'watchman_quest', effect: { knowledge: 10 } },
        { text: '「迴廊怎麼去？」', next: 'watchman_corridor', effect: { knowledge: 10, unlock: 'loc_corridor' } },
        { text: '離開', next: null },
      ],
    },
    watchman_quest: {
      speaker: '守門人',
      text: '「你來找答案。答案就在湖底。但你需要一把鑰匙。」\n「鑰匙不在這裡。在學校。在圖書館。」',
      choices: [
        { text: '「怎麼去學校？」', next: 'watchman_school', effect: { knowledge: 10 } },
        { text: '離開', next: null },
      ],
    },
    watchman_school: {
      speaker: '守門人',
      text: '「沿著鏡湖東側的小路走。學校就在那裡。\n晞咕萊雅管理那裡。她知道鑰匙在哪。」',
      choices: [
        { text: '前往學校', next: null, effect: { unlock: 'loc_holy_cross' } },
      ],
    },
    watchman_corridor: {
      speaker: '守門人',
      text: '「迴廊連接所有世界線。」\n「你需要三樣東西：理解、鑰匙、和勇氣。」',
      choices: [
        { text: '「我準備好了」', next: null, effect: { knowledge: 15, unlock: 'loc_corridor' } },
        { text: '離開', next: null },
      ],
    },

    greeting_wings: {
      speaker: '翅翼少女',
      text: '你在書頁的影像中看到一個金屬翅膀的女孩。\n她停下來，轉頭看向你。\n「你能看到我？」',
      choices: [
        { text: '「我能。你是誰？」', next: 'wings_who' },
        { text: '合上書', next: null },
      ],
    },
    wings_who: {
      speaker: '翅翼少女',
      text: '「我不確定。我在這裡很久了。」\n「你知道怎麼離開嗎？」',
      choices: [
        { text: '「你知道迴廊嗎？」', next: 'wings_corridor', effect: { bond: { wings: 15 } } },
        { text: '「我不知道」', next: null },
      ],
    },
    wings_corridor: {
      speaker: '翅翼少女',
      text: '「迴廊？」她的眼睛亮了。\n「如果你找到了，能告訴我嗎？」',
      choices: [
        { text: '答應她', next: null, effect: { bond: { wings: 10 } } },
      ],
    },

    greeting_oldman: {
      speaker: '記憶老人',
      text: '老人看著你。\n「別的？」他想了想。\n「你有什麼可以交換的？我對情感有興趣。」',
      choices: [
        { text: '「什麼情感？」', next: 'oldman_emotions' },
        { text: '離開', next: null },
      ],
    },
    oldman_emotions: {
      speaker: '記憶老人',
      text: '「恐懼、快樂、悲傷。你有嗎？」\n他舉起一個小瓶子，裡面的光在閃爍。',
      choices: [
        { text: '買記憶碎片（交換冰層樣本）', next: 'oldman_trade', requires: { item: 'item_ice_sample' }, effect: { items: ['item_memory_orb'], knowledge: 15 } },
        { text: '「我沒東西換」', next: null },
      ],
    },
    oldman_trade: {
      speaker: '記憶老人',
      text: '「好東西。」他接過樣本，舉到光線下。\n他遞給你一個小瓶子。\n裡面的光飛出來，鑽進你的腦子。你看到了一段記憶。',
      choices: [
        { text: '收下記憶', next: null },
      ],
    },

    corridor_start: {
      speaker: '???',
      text: '迴廊的入口在鏡湖下方。\n門上沒有把手。只有一行字：「你在找什麼？」',
      choices: [
        { text: '「答案。」', next: 'corridor_answer', effect: { knowledge: 10 } },
        { text: '「我自己。」', next: 'corridor_self', effect: { knowledge: 10 } },
        { text: '「我想回家。」', next: 'corridor_home', effect: { knowledge: 10 } },
        { text: '使用迴廊鑰匙', next: 'corridor_key', requires: { item: 'item_key_corridor' } },
      ],
    },
    corridor_answer: {
      speaker: '迴廊',
      text: '門打開了。\n兩側的門不斷開合。每一扇門後面都是一個不同的世界。',
      choices: [
        { text: '進入迴廊', next: null, effect: { unlock: 'ending_corridor' } },
      ],
    },
    corridor_self: {
      speaker: '迴廊',
      text: '門緩緩打開。\n你在走廊中看到了自己。不是現在的自己。是可能的自己。',
      choices: [
        { text: '面對自己', next: null, effect: { unlock: 'ending_corridor', knowledge: 20, unlocks: ['loc_abandoned_mine', 'loc_hall_of_heroes'] } },
      ],
    },
    corridor_home: {
      speaker: '迴廊',
      text: '門開了一條縫。從縫隙中傳來熟悉的氣味。\n然後門關上了。',
      choices: [
        { text: '再次推門', next: 'corridor_push' },
      ],
    },
    corridor_key: {
      speaker: '迴廊',
      text: '你把鑰匙插入門上的鎖孔。\n門打開了。你走進迴廊。',
      choices: [
        { text: '深入', next: null, effect: { unlock: 'ending_corridor', knowledge: 25 } },
      ],
    },
    corridor_push: {
      speaker: '迴廊',
      text: '門上出現了新的字：「你還沒有準備好。」',
      choices: [
        { text: '「我準備好了」', next: 'corridor_answer' },
      ],
    },

    // 決戰 / 結局
    ending_corridor: {
      speaker: '旁白',
      text: '你在迴廊中行走。無盡的走廊，兩側的門不斷開合。\n你看到了時間在流動。你看到了你自己。\n然後，一切安靜下來。',
      choices: [
        { text: '繼續', next: 'ending_final' },
      ],
    },
    ending_final: {
      speaker: '旁白',
      text: '你站在迴廊的盡頭。\n面前是一面鏡子。鏡子裡是你自己。\n但你不一樣了。\n\n— 完 —',
      choices: [
        { text: '重新開始', next: 'restart' },
      ],
    },
  },
};

// World line descriptions for card tooltips
const WORLD_LINES = {
  W01: { name: '主世界線', desc: '正常的時間流動。靈子與電子共存。' },
  W02: { name: '琥珀紀元', desc: '絕對無魔的中世紀村落。物理法則統治一切。' },
  W03: { name: '軌道居住站', desc: '低靈子環境，電子設備精度最高。' },
  W04: { name: '灰燼紀元', desc: '不穩定的靈子。電子設備大量損壞。' },
  '迴廊': { name: '迴廊', desc: '連接所有世界線的橋樑。' },
  '夢境層': { name: '夢境層', desc: '跨世界共享的夢境空間。' },
};

// NPC schedules (simplified for game)
const NPC_SCHEDULES = {
  char_hikuraya: { morning: 'loc_library', afternoon: 'loc_library', evening: 'loc_library' },
  char_red: { morning: 'loc_market', afternoon: 'loc_market', evening: 'loc_market' },
  char_watchman: { morning: 'loc_mirror_lake', afternoon: 'loc_mirror_lake', evening: 'loc_mirror_lake' },
  char_old_man: { morning: 'loc_market', afternoon: 'loc_market', evening: 'loc_market' },
};

// Export as global for browser and Electron
if (typeof module !== "undefined" && module.exports) {
  module.exports = { CARDS, WORLD_LINES, NPC_SCHEDULES };
} else {
  window.CARDS_DATA = { CARDS, WORLD_LINES, NPC_SCHEDULES };
}
