# Atlassian 集成配置文件
# 用於配置 Rovo Dev Agents 和 Atlassian 服務的集成

atlassian:
  # 基本認證配置
  api_token: "${ATLASSIAN_API_TOKEN}"
  cloud_id: "${ATLASSIAN_CLOUD_ID}"
  user_email: "${ATLASSIAN_USER_EMAIL}"
  
  # Confluence 配置
  confluence:
    base_url: "https://${ATLASSIAN_DOMAIN}.atlassian.net/wiki"
    default_space: "DEV"
    api_version: "v2"
    page_templates:
      technical_doc: "technical-documentation-template"
      api_doc: "api-documentation-template"
      meeting_notes: "meeting-notes-template"
    
  # Jira 配置  
  jira:
    base_url: "https://${ATLASSIAN_DOMAIN}.atlassian.net"
    default_project: "UAI"
    api_version: "3"
    issue_types:
      task: "Task"
      bug: "Bug"
      story: "Story"
      epic: "Epic"
    priorities:
      highest: "Highest"
      high: "High"
      medium: "Medium"
      low: "Low"
      lowest: "Lowest"
      
  # Bitbucket 配置
  bitbucket:
    base_url: "https://api.bitbucket.org/2.0"
    workspace: "${BITBUCKET_WORKSPACE}"
    default_repo: "unified-ai-project"
    
  # Rovo Dev Agents 配置
  rovo_dev:
    enabled: true
    max_concurrent_requests: 5
    timeout: 30
    retry_attempts: 3
    cache_ttl: 300  # 5 分鐘
    
    # 代理能力配置
    capabilities:
      - name: "code_analysis"
        description: "分析代碼結構和質量"
        enabled: true
      - name: "documentation_generation"
        description: "自動生成技術文檔"
        enabled: true
      - name: "issue_tracking"
        description: "智能問題追蹤和管理"
        enabled: true
      - name: "project_management"
        description: "項目進度管理和報告"
        enabled: true
      - name: "code_review"
        description: "自動化代碼審查"
        enabled: true
        
    # 自動化規則配置
    automation:
      auto_create_docs: true
      auto_link_issues: true
      auto_update_status: true
      notification_channels:
        - type: "confluence"
          space: "DEV"
        - type: "jira"
          project: "UAI"
          
# HSP 集成配置
hsp_integration:
  agent_id: "rovo-dev-agent"
  capabilities_topic: "hsp/capabilities/rovo-dev"
  task_request_topic: "hsp/tasks/rovo-dev"
  task_result_topic: "hsp/results/rovo-dev"
  
  # 任務類型映射
  task_mappings:
    "create_confluence_page": "documentation_generation"
    "create_jira_issue": "issue_tracking"
    "analyze_code": "code_analysis"
    "review_pull_request": "code_review"
    "generate_report": "project_management"

# 安全配置
security:
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
  
  rate_limiting:
    requests_per_minute: 60
    burst_size: 10
    
  access_control:
    allowed_domains:
      - "*.atlassian.net"
      - "api.bitbucket.org"
    
    required_permissions:
      confluence:
        - "read"
        - "write"
        - "admin"
      jira:
        - "browse"
        - "create"
        - "edit"
        - "admin"
      bitbucket:
        - "repository:read"
        - "repository:write"
        - "pullrequest:read"
        - "pullrequest:write"

# 監控和日誌配置
monitoring:
  metrics:
    enabled: true
    endpoint: "/metrics"
    
  logging:
    level: "INFO"
    format: "json"
    file: "logs/atlassian_integration.log"
    max_size: "100MB"
    backup_count: 5
    
  health_check:
    enabled: true
    interval: 60  # 秒
    timeout: 10   # 秒
    endpoints:
      - name: "confluence"
        url: "${CONFLUENCE_BASE_URL}/rest/api/space"
      - name: "jira"
        url: "${JIRA_BASE_URL}/rest/api/3/myself"
      - name: "bitbucket"
        url: "https://api.bitbucket.org/2.0/user"

# 開發和測試配置
development:
  mock_mode: false
  test_space: "TEST"
  test_project: "TEST"
  debug_logging: true
  
  # 測試數據
  test_data:
    confluence_page_title: "Test Page - Automated"
    jira_issue_summary: "Test Issue - Automated"
    test_repository: "test-repo"