decompose_user_intent: |
  Based on the user query and available capabilities, decompose the request into subtasks.
  User query: {user_query}
  Available capabilities: {capabilities}
  Return a JSON array of subtasks.

integrate_subtask_results: |
  Integrate the results from subtasks to answer the original query.
  Original query: {original_query}
  Subtask results: {results}
  Provide a coherent response.