@echo off
chcp 65001 >nul 2>&1
setlocal enabledelayedexpansion
title Unified AI Project - Automated Backup
color 0B

:: Automated backup script for Unified AI Project
:: 自动化备份脚本

echo ==========================================
echo   🔒 Unified AI Project - Automated Backup
echo ==========================================
echo.

:: Set backup directory with timestamp
set "BACKUP_ROOT=%~dp0..\backups"
set "TIMESTAMP=%date:~-4%%date:~-10,2%%date:~-7,2%_%time:~0,2%%time:~3,2%%time:~6,2%"
set "TIMESTAMP=!TIMESTAMP: =0!"

:: Remove colons and spaces from timestamp
set "TIMESTAMP=!TIMESTAMP::=!"

:: Create backup directory
set "BACKUP_DIR=%BACKUP_ROOT%\backup_!TIMESTAMP!"
echo [INFO] Creating backup directory: !BACKUP_DIR!
mkdir "!BACKUP_DIR!" 2>nul

if not exist "!BACKUP_DIR!" (
    echo [ERROR] Failed to create backup directory
    exit /b 1
)

:: Set project root
set "PROJECT_ROOT=%~dp0.."
if "!PROJECT_ROOT:~-1!"=="\" set "PROJECT_ROOT=!PROJECT_ROOT:~0,-1!"

echo [INFO] Starting automated backup of Unified AI Project...
echo [INFO] Backup timestamp: !TIMESTAMP!
echo.

:: Backup core directories
echo [INFO] Backing up core directories...

:: Backup apps directory
if exist "!PROJECT_ROOT!\apps" (
    echo [INFO] Backing up apps directory...
    xcopy "!PROJECT_ROOT!\apps" "!BACKUP_DIR!\apps\" /E /I /H /Y >nul 2>&1
    if !errorlevel! equ 0 (
        echo [SUCCESS] Apps directory backed up successfully
    ) else (
        echo [WARNING] Failed to backup apps directory
    )
)

:: Backup packages directory
if exist "!PROJECT_ROOT!\packages" (
    echo [INFO] Backing up packages directory...
    xcopy "!PROJECT_ROOT!\packages" "!BACKUP_DIR!\packages\" /E /I /H /Y >nul 2>&1
    if !errorlevel! equ 0 (
        echo [SUCCESS] Packages directory backed up successfully
    ) else (
        echo [WARNING] Failed to backup packages directory
    )
)

:: Backup tools directory
if exist "!PROJECT_ROOT!\tools" (
    echo [INFO] Backing up tools directory...
    xcopy "!PROJECT_ROOT!\tools" "!BACKUP_DIR!\tools\" /E /I /H /Y >nul 2>&1
    if !errorlevel! equ 0 (
        echo [SUCCESS] Tools directory backed up successfully
    ) else (
        echo [WARNING] Failed to backup tools directory
    )
)

:: Backup scripts directory
if exist "!PROJECT_ROOT!\scripts" (
    echo [INFO] Backing up scripts directory...
    xcopy "!PROJECT_ROOT!\scripts" "!BACKUP_DIR!\scripts\" /E /I /H /Y >nul 2>&1
    if !errorlevel! equ 0 (
        echo [SUCCESS] Scripts directory backed up successfully
    ) else (
        echo [WARNING] Failed to backup scripts directory
    )
)

:: Backup training directory
if exist "!PROJECT_ROOT!\training" (
    echo [INFO] Backing up training directory...
    xcopy "!PROJECT_ROOT!\training" "!BACKUP_DIR!\training\" /E /I /H /Y >nul 2>&1
    if !errorlevel! equ 0 (
        echo [SUCCESS] Training directory backed up successfully
    ) else (
        echo [WARNING] Failed to backup training directory
    )
)

:: Backup configuration files
echo [INFO] Backing up configuration files...
set "CONFIG_FILES=package.json pnpm-workspace.yaml README.md"
for %%f in (!CONFIG_FILES!) do (
    if exist "!PROJECT_ROOT!\%%f" (
        copy "!PROJECT_ROOT!\%%f" "!BACKUP_DIR!\" >nul 2>&1
        if !errorlevel! equ 0 (
            echo [SUCCESS] %%f backed up successfully
        ) else (
            echo [WARNING] Failed to backup %%f
        )
    )
)

:: Backup documentation files
echo [INFO] Backing up documentation files...
for %%f in (*.md) do (
    if exist "!PROJECT_ROOT!\%%f" (
        copy "!PROJECT_ROOT!\%%f" "!BACKUP_DIR!\" >nul 2>&1
        if !errorlevel! equ 0 (
            echo [SUCCESS] %%f backed up successfully
        ) else (
            echo [WARNING] Failed to backup %%f
        )
    )
)

:: Create backup info file
echo [INFO] Creating backup information file...
(
    echo Unified AI Project Backup
    echo =======================
    echo Backup Timestamp: !TIMESTAMP!
    echo Backup Directory: !BACKUP_DIR!
    echo Backup Date: %date%
    echo Backup Time: %time%
    echo.
    echo This backup was automatically generated by automated-backup.bat
    echo ===============================================================
) > "!BACKUP_DIR!\backup_info.txt"

echo [SUCCESS] Backup information file created

:: Verify backup integrity
echo [INFO] Verifying backup integrity...
set "backup_size=0"
for /f "delims=" %%i in ('dir "!BACKUP_DIR!" /s /b') do (
    if exist "%%i" (
        for /f "tokens=4" %%s in ('dir "!BACKUP_DIR!" /s ^| find "File(s)"') do set "backup_size=%%s"
    )
)

echo [INFO] Backup size: !backup_size! bytes

:: Clean up old backups (keep last 10)
echo [INFO] Cleaning up old backups (keeping last 10)...
for /f "skip=10 delims=" %%i in ('dir "!BACKUP_ROOT!" /b /o-d 2^>nul') do (
    echo [INFO] Removing old backup: %%i
    rd /s /q "!BACKUP_ROOT!\%%i" >nul 2>&1
)

echo.
echo ==========================================
echo   ✅ Automated Backup Completed Successfully
echo ==========================================
echo.
echo Backup Location: !BACKUP_DIR!
echo Backup Size: !backup_size! bytes
echo.
echo [INFO] Backup timestamp: !TIMESTAMP!
echo.

pause