# Unified AI Project 性能优化配置文件
performance:
  # 系统资源监控配置
  resource_monitoring:
    enabled: true
    check_interval: 5  # 资源检查间隔（秒）
    cpu_warning_threshold: 80.0
    cpu_critical_threshold: 90.0
    memory_warning_threshold: 75.0
    memory_critical_threshold: 85.0
    disk_warning_threshold: 80.0
    disk_critical_threshold: 90.0

  # 缓存配置
  caching:
    enabled: true
    default_ttl: 300  # 默认缓存时间（秒）
    max_cache_size: 1000  # 最大缓存条目数
    lru_enabled: true  # 启用LRU淘汰策略

  # 并行处理配置
  parallel_processing:
    max_workers: 4  # 最大并行工作线程数
    task_queue_size: 100  # 任务队列大小
    timeout: 30  # 任务超时时间（秒）

  # API优化配置
  api_optimization:
    compression_enabled: true  # 启用响应压缩
    keepalive_timeout: 120  # Keep-alive超时时间（秒）
    max_connections: 100  # 最大连接数

  # 数据库优化配置
  database_optimization:
    connection_pool_size: 20  # 连接池大小
    query_timeout: 30  # 查询超时时间（秒）
    batch_size: 100  # 批量操作大小

  # 日志优化配置
  logging:
    level: "INFO"  # 日志级别
    async_logging: true  # 异步日志记录
    max_log_size: 10485760  # 最大日志文件大小（10MB）
    backup_count: 5  # 日志备份文件数量