name: Docs Link Check

on:
  pull_request:
    paths:
      - '**/*.md'
      - 'docs/**'
      - 'scripts/**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  link-check:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f apps/backend/requirements.txt ]; then pip install -r apps/backend/requirements.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run docs link check (no fix)
        shell: bash
        run: |
          python scripts/project_ai_orchestrator.py --check-docs -v --md-scope all

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docs-link-check-report
          path: |
            docs_link_check_errors.json
            docs_link_check_errors.txt
            doc_update_report.md
          if-no-files-found: ignore